# Generated by Django 6.0.2 on 2026-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=100)),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Allow others to view/download')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
    ]
